import { Tables } from "../../types/supabase";

// Adresler için örnek veri
export const sampleAddresses: Tables<'addresses'>[] = [
  {
    id: 'address-uuid-1',
    user_id: 'user-uuid-1',
    name: 'Ev',
    type: 'home',
    address_line1: 'Atatürk Cad. No:123 Daire:5',
    address_line2: null,
    city: 'İstanbul',
    state: 'İstanbul',
    country: 'Türkiye',
    postal_code: '34100',
    latitude: 41.0082,
    longitude: 28.9784,
    is_default: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'address-uuid-2',
    user_id: 'user-uuid-1',
    name: 'İş',
    type: 'work',
    address_line1: 'İnönü Cad. No:45 Kat:3',
    address_line2: 'İş Merkezi',
    city: 'İstanbul',
    state: 'İstanbul',
    country: 'Türkiye',
    postal_code: '34220',
    latitude: 41.0360,
    longitude: 28.9877,
    is_default: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'address-uuid-3',
    user_id: 'user-uuid-1',
    name: 'Yazlık',
    type: 'vacation',
    address_line1: 'Sahil Sok. No:12',
    address_line2: 'Yazlık Sitesi',
    city: 'Muğla',
    state: 'Muğla',
    country: 'Türkiye',
    postal_code: '48000',
    latitude: 37.2154,
    longitude: 28.3636,
    is_default: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'address-uuid-4',
    user_id: 'user-uuid-2',
    name: 'Ev',
    type: 'home',
    address_line1: 'Bağdat Cad. No:56 Daire:8',
    address_line2: null,
    city: 'İstanbul',
    state: 'İstanbul',
    country: 'Türkiye',
    postal_code: '34710',
    latitude: 40.9777,
    longitude: 29.0590,
    is_default: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'address-uuid-5',
    user_id: 'user-uuid-3',
    name: 'Ev',
    type: 'home',
    address_line1: 'Kızılay Meydanı No:3',
    address_line2: null,
    city: 'Ankara',
    state: 'Ankara',
    country: 'Türkiye',
    postal_code: '06420',
    latitude: 39.9208,
    longitude: 32.8541,
    is_default: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
]; 